# Generated by Django 2.2.13 on 2020-08-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='market_price',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=5, verbose_name='市场价'),
        ),
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.CharField(default='0.0', max_length=50, verbose_name='出版社'),
        ),
    ]
