# Generated by Django 2.2.13 on 2020-08-10 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_author'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
