# Generated by Django 2.2.13 on 2020-08-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='书名')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='定价')),
                ('market_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='零售价')),
                ('pub', models.CharField(default='', max_length=50, verbose_name='出版社')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
            ],
        ),
    ]
